version: "3.9"
services:
  mysql:
    image: node-app-image
    container_name: node-app
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'clubs'
    ports:
      - "3000:3000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST='localhost'
      - MYSQL_PORT=3000
      - MYSQL_USER='root'
      - MYSQL_PASSWORD=''
      - MYSQL_DATABASE='clubs'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
